// Bilingual service-card data for the About page's "Our Services" section.
// Shaped like config/categories.js (nameEn/nameTe shown side by side on the
// card, independent of the active language toggle) so both languages are
// always visible at once, per the About page spec.
export const ABOUT_SERVICES = [
  {
    key: 'residential-plots',
    icon: 'LandPlot',
    nameEn: 'Residential Plots',
    nameTe: 'రెసిడెన్షియల్ ప్లాట్లు',
    descriptionEn: 'Verified residential plots ready for your dream home.',
    descriptionTe: 'మీ కలల ఇంటి కోసం ధృవీకరించబడిన రెసిడెన్షియల్ ప్లాట్లు.',
    to: '/properties/category/residential-plots',
  },
  {
    key: 'open-plots',
    icon: 'Trees',
    nameEn: 'Open Plots',
    nameTe: 'ఓపెన్ ప్లాట్లు',
    descriptionEn: 'Open plots in developing localities with clear titles.',
    descriptionTe: 'స్పష్టమైన టైటిల్స్‌తో అభివృద్ధి చెందుతున్న ప్రాంతాల్లో ఓపెన్ ప్లాట్లు.',
    to: '/properties/category/open-plots',
  },
  {
    key: 'commercial-properties',
    icon: 'Store',
    nameEn: 'Commercial Properties',
    nameTe: 'వాణిజ్య ఆస్తులు',
    descriptionEn: 'Shops, showrooms and commercial spaces for your business.',
    descriptionTe: 'మీ వ్యాపారానికి దుకాణాలు, షోరూమ్‌లు మరియు వాణిజ్య స్థలాలు.',
    to: '/properties/category/commercial-plots',
  },
  {
    key: 'apartments',
    icon: 'Building2',
    nameEn: 'Apartments',
    nameTe: 'అపార్ట్‌మెంట్లు',
    descriptionEn: 'Ready-to-move and under-construction apartments.',
    descriptionTe: 'నివసించడానికి సిద్ధంగా ఉన్న మరియు నిర్మాణంలో ఉన్న అపార్ట్‌మెంట్లు.',
    to: '/properties/category/apartments',
  },
  {
    key: 'independent-houses',
    icon: 'Home',
    nameEn: 'Independent Houses',
    nameTe: 'ఇండిపెండెంట్ హౌస్‌లు',
    descriptionEn: 'Independent houses with verified ownership documents.',
    descriptionTe: 'ధృవీకరించబడిన యాజమాన్య పత్రాలతో ఇండిపెండెంట్ హౌస్‌లు.',
    to: '/properties/category/independent-houses',
  },
  {
    key: 'gated-communities',
    icon: 'ShieldCheck',
    nameEn: 'Gated Communities',
    nameTe: 'గేటెడ్ కమ్యూనిటీలు',
    descriptionEn: 'Secure gated communities with modern amenities.',
    descriptionTe: 'ఆధునిక సౌకర్యాలతో సురక్షితమైన గేటెడ్ కమ్యూనిటీలు.',
    to: '/properties/category/gated-communities',
  },
  {
    key: 'ventures',
    icon: 'Map',
    nameEn: 'Ventures',
    nameTe: 'వెంచర్లు',
    descriptionEn: 'Approved ventures with transparent layouts and pricing.',
    descriptionTe: 'పారదర్శక లేఅవుట్‌లు మరియు ధరలతో ఆమోదించబడిన వెంచర్లు.',
    to: '/ventures',
  },
  {
    key: 'agricultural-lands',
    icon: 'Wheat',
    nameEn: 'Agricultural Lands',
    nameTe: 'వ్యవసాయ భూములు',
    descriptionEn: 'Fertile agricultural lands verified before listing.',
    descriptionTe: 'లిస్టింగ్‌కు ముందు ధృవీకరించబడిన సారవంతమైన వ్యవసాయ భూములు.',
    to: '/properties/category/agricultural-lands',
  },
  {
    key: 'buyer-assistance',
    icon: 'UserCheck',
    nameEn: 'Buyer Assistance',
    nameTe: 'కొనుగోలుదారు సహాయం',
    descriptionEn: 'Guided support to help buyers find the right property.',
    descriptionTe: 'సరైన ఆస్తిని కనుగొనడంలో కొనుగోలుదారులకు మార్గదర్శక సహాయం.',
    to: '/register/buyer',
  },
  {
    key: 'seller-support',
    icon: 'Handshake',
    nameEn: 'Seller Support',
    nameTe: 'విక్రేత మద్దతు',
    descriptionEn: 'Help publishing, managing and promoting your listing.',
    descriptionTe: 'మీ లిస్టింగ్‌ను ప్రచురించడం, నిర్వహించడం మరియు ప్రచారం చేయడంలో సహాయం.',
    to: '/register/seller',
  },
  {
    key: 'site-visit-coordination',
    icon: 'CalendarCheck',
    nameEn: 'Site Visit Coordination',
    nameTe: 'సైట్ విజిట్ సమన్వయం',
    descriptionEn: 'We help schedule and coordinate property site visits.',
    descriptionTe: 'ఆస్తి సైట్ విజిట్‌లను షెడ్యూల్ చేయడంలో మరియు సమన్వయం చేయడంలో మేము సహాయం చేస్తాము.',
    to: '/contact',
  },
  {
    key: 'property-enquiry-support',
    icon: 'MessageCircleQuestion',
    nameEn: 'Property Enquiry Support',
    nameTe: 'ఆస్తి విచారణ మద్దతు',
    descriptionEn: 'Quick responses to your property-related questions.',
    descriptionTe: 'మీ ఆస్తి సంబంధిత ప్రశ్నలకు త్వరిత సమాధానాలు.',
    to: '/contact',
  },
];
