import {
  ArrowUpDown, Zap, Shield, Dumbbell, ToyBrick, Car, Droplets, Droplet,
  Flower2, BrickWall, Waves, Building, Footprints, Flame, Lamp, TreePine,
  Road, StretchVertical, Drill, Warehouse, Container, Apple, Sparkles,
  Lock, Camera, CarFront, Gamepad2, Trophy, PhoneCall, CloudRain, Recycle,
  Sun, Plug, AirVent, ConciergeBell, Users, Wifi, Bath, ShoppingCart,
  CircleParking, Bus, ArrowLeftRight, PlugZap, RotateCw, Home, Package,
  LandPlot, CookingPot, Armchair, DoorOpen, Truck, Briefcase,
  Landmark, Coffee,
} from 'lucide-react';

const AMENITY_ICONS = {
  lift: ArrowUpDown,
  'power backup': Zap,
  backup: Zap,
  security: Shield,
  gym: Dumbbell,
  'children play area': ToyBrick,
  'play area': ToyBrick,
  parking: Car,
  'car parking': Car,
  'water supply': Droplets,
  water: Droplets,
  '24 7 water': Droplets,
  'municipal water': Droplets,
  garden: Flower2,
  'landscaped garden': Flower2,
  'compound wall': BrickWall,
  'swimming pool': Waves,
  pool: Waves,
  clubhouse: Building,
  'club house': Building,
  'jogging track': Footprints,
  'walking track': Footprints,
  'fire safety': Flame,
  fire: Flame,
  'street lighting': Lamp,
  'street lights': Lamp,
  streetlight: Lamp,
  'underground drainage': Droplet,
  drainage: Droplet,
  'avenue plantation': TreePine,
  plantation: TreePine,
  'road access': Road,
  road: Road,
  'height clearance': StretchVertical,
  'water canal': Waves,
  canal: Waves,
  'canal water': Waves,
  'river nearby': Waves,
  'drip irrigation': Droplet,
  irrigation: Droplet,
  borewell: Drill,
  electricity: Zap,
  'farm shed': Warehouse,
  'water tank': Container,
  orchard: Apple,
  'gated entrance': Lock,
  'gated security': Shield,
  cctv: Camera,
  visitor: CarFront,
  'visitor parking': CarFront,
  'indoor games': Gamepad2,
  'outdoor games': Trophy,
  intercom: PhoneCall,
  'rainwater harvesting': CloudRain,
  'sewage treatment plant': Recycle,
  'solar power': Sun,
  'solar water heater': Sun,
  generator: Plug,
  'central ac': AirVent,
  reception: ConciergeBell,
  'conference room': Users,
  pantry: Coffee,
  'internet connectivity': Wifi,
  washrooms: Bath,
  washroom: Bath,
  supermarket: ShoppingCart,
  'parking space': CircleParking,
  'high footfall area': Users,
  'public transport nearby': Bus,
  'loading unloading access': ArrowLeftRight,
  'loading area': Package,
  'loading dock': Package,
  'truck parking': Truck,
  '3 phase electricity': Zap,
  '3 phase power': Zap,
  transformer: PlugZap,
  'transformer nearby': PlugZap,
  'motor pump': RotateCw,
  'farm house': Home,
  'storage shed': Warehouse,
  'trees plantation': TreePine,
  'main road access': Road,
  'main road facing': Road,
  'highway access': Road,
  'highway nearby': Road,
  'heavy vehicle access': Truck,
  'industrial water': Droplets,
  'office room': Briefcase,
  terrace: LandPlot,
  balcony: DoorOpen,
  'modular kitchen': CookingPot,
  'pooja room': Sparkles,
  'store room': Package,
  'servant room': Users,
  'community hall': Building,
  temple: Landmark,
  'children park': ToyBrick,
'cc roads': Road,
  'bt roads': Road,
  'water connection': Droplets,
  fencing: BrickWall,
  'outdoor seating': Armchair,
  'sports area': Trophy,
};

const normalize = (name) =>
  String(name || '')
    .trim()
    .toLowerCase()
    .replace(/[’']/g, '')
    .replace(/&/g, 'and')
    .replace(/[-/×x*]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();

export function getAmenityIcon(amenity) {
  return AMENITY_ICONS[normalize(amenity)] || Sparkles;
}