export const CATEGORIES = [
  {
    slug: 'residential-plots',
    ruleKey: 'residentialPlot',
    nameEn: 'Residential Plots',
    nameTe: 'రెసిడెన్షియల్ ప్లాట్లు',
    icon: 'LandPlot',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=60',
  },
  {
    slug: 'open-plots',
    ruleKey: 'openPlot',
    nameEn: 'Open Plots',
    nameTe: 'ఓపెన్ ప్లాట్లు',
    icon: 'Trees',
    image: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=800&q=60',
  },
  {
    slug: 'commercial-plots',
    ruleKey: 'commercialPlot',
    nameEn: 'Commercial Plots',
    nameTe: 'కమర్షియల్ ప్లాట్లు',
    icon: 'Store',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=60',
  },
  {
    slug: 'apartments',
    ruleKey: 'apartment',
    nameEn: 'Apartments',
    nameTe: 'అపార్ట్‌మెంట్లు',
    icon: 'Building2',
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=800&q=60',
  },
  {
    slug: 'independent-houses',
    ruleKey: 'independentHouse',
    nameEn: 'Independent Houses',
    nameTe: 'ఇండిపెండెంట్ హౌస్‌లు',
    icon: 'Home',
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=800&q=60',
  },
  {
    slug: 'gated-communities',
    ruleKey: 'gatedCommunity',
    nameEn: 'Gated Communities',
    nameTe: 'గేటెడ్ కమ్యూనిటీలు',
    icon: 'ShieldCheck',
    image: 'https://images.unsplash.com/photo-1592595896616-c37162298647?auto=format&fit=crop&w=800&q=60',
  },
  {
    slug: 'ventures',
    ruleKey: 'venture',
    nameEn: 'Ventures',
    nameTe: 'వెంచర్లు',
    icon: 'Map',
    image: 'https://images.unsplash.com/photo-1516156008625-3a9d6067fab5?auto=format&fit=crop&w=800&q=60',
  },
  {
    slug: 'agricultural-lands',
    ruleKey: 'agriculturalLand',
    nameEn: 'Agricultural Lands',
    nameTe: 'వ్యవసాయ భూములు',
    icon: 'Wheat',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=60',
  },
  {
    slug: 'flats',
    ruleKey: 'apartment',
    nameEn: 'Flats',
    nameTe: 'ఫ్లాట్లు',
    icon: 'Building',
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60',
  },
  {
    slug: 'villas',
    ruleKey: 'independentHouse',
    nameEn: 'Villas',
    nameTe: 'విల్లాలు',
    icon: 'Castle',
    image: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60',
  },
  {
    slug: 'offices',
    ruleKey: 'commercialPlot',
    nameEn: 'Office Spaces',
    nameTe: 'ఆఫీస్ స్పేస్‌లు',
    icon: 'Briefcase',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=60',
  },
  {
    slug: 'shops',
    ruleKey: 'commercialPlot',
    nameEn: 'Shops',
    nameTe: 'దుకాణాలు',
    icon: 'ShoppingBag',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=60',
  },
  {
    slug: 'warehouses',
    ruleKey: 'commercialPlot',
    nameEn: 'Warehouses',
    nameTe: 'గోడౌన్‌లు',
    icon: 'Warehouse',
    image: 'https://images.unsplash.com/photo-1553413077-190083ec01ff?auto=format&fit=crop&w=800&q=60',
  },
  {
    slug: 'farm-lands',
    ruleKey: 'agriculturalLand',
    nameEn: 'Farm Lands',
    nameTe: 'పొలాలు',
    icon: 'Tractor',
    image: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=800&q=60',
  },
  {
    slug: 'commercial-buildings',
    ruleKey: 'commercialPlot',
    nameEn: 'Commercial Buildings',
    nameTe: 'కమర్షియల్ భవనాలు',
    icon: 'Building2',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=60',
  },
];

export function getCategoryBySlug(slug) {
  return CATEGORIES.find((c) => c.slug === slug);
}

export function getCategoryByRuleKey(ruleKey) {
  return CATEGORIES.find((c) => c.ruleKey === ruleKey);
}
