export const DASHBOARD_NAV = {
  buyer: [
    { key: 'properties', path: '/buyer/properties', labelKey: 'nav.browseProperties', icon: 'Search' },
    { key: 'my-properties', path: '/buyer/my-properties', labelKey: 'nav.myProperties', icon: 'Building2' },
    { key: 'new-property', path: '/buyer/properties/new', labelKey: 'nav.addProperty', icon: 'PlusSquare' },
    { key: 'favourites', path: '/buyer/favourites', labelKey: 'nav.favourites', icon: 'Heart' },
    { key: 'interests', path: '/buyer/interests', labelKey: 'nav.interests', icon: 'MessageSquareHeart' },
    { key: 'visits', path: '/buyer/visits', labelKey: 'nav.visits', icon: 'CalendarCheck' },
    { key: 'notifications', path: '/buyer/notifications', labelKey: 'nav.notifications', icon: 'Bell' },
    { key: 'settings', path: '/buyer/settings', labelKey: 'nav.settings', icon: 'Settings' },
    { key: 'profile', path: '/buyer/profile', labelKey: 'nav.profile', icon: 'UserCircle' },
  ],
  seller: [
    { key: 'dashboard', path: '/seller/dashboard', labelKey: 'nav.dashboard', icon: 'LayoutDashboard' },
    { key: 'properties', path: '/seller/properties', labelKey: 'nav.myProperties', icon: 'Building2' },
    { key: 'new-property', path: '/seller/properties/new', labelKey: 'nav.addProperty', icon: 'PlusSquare' },
    { key: 'enquiries', path: '/seller/enquiries', labelKey: 'nav.enquiries', icon: 'Inbox' },
    { key: 'visits', path: '/seller/visits', labelKey: 'nav.visits', icon: 'CalendarCheck' },
    { key: 'analytics', path: '/seller/analytics', labelKey: 'profileMenu.analytics', icon: 'BarChart3' },
    { key: 'notifications', path: '/seller/notifications', labelKey: 'nav.notifications', icon: 'Bell' },
    { key: 'settings', path: '/seller/settings', labelKey: 'nav.settings', icon: 'Settings' },
    { key: 'profile', path: '/seller/profile', labelKey: 'nav.profile', icon: 'UserCircle' },
  ],
  mediator: [
    { key: 'dashboard', path: '/mediator/dashboard', labelKey: 'nav.dashboard', icon: 'LayoutDashboard' },
    { key: 'leads', path: '/mediator/leads', labelKey: 'nav.leads', icon: 'Users' },
    { key: 'properties', path: '/mediator/properties', labelKey: 'nav.properties', icon: 'Building2' },
    { key: 'new-property', path: '/mediator/properties/new', labelKey: 'nav.addProperty', icon: 'PlusSquare' },
    { key: 'visits', path: '/mediator/visits', labelKey: 'nav.visits', icon: 'CalendarCheck' },
    { key: 'follow-ups', path: '/mediator/follow-ups', labelKey: 'nav.followUps', icon: 'PhoneCall' },
    { key: 'commission', path: '/mediator/commission', labelKey: 'profileMenu.commissionHistory', icon: 'HandCoins' },
    { key: 'notifications', path: '/mediator/notifications', labelKey: 'nav.notifications', icon: 'Bell' },
    { key: 'settings', path: '/mediator/settings', labelKey: 'nav.settings', icon: 'Settings' },
    { key: 'profile', path: '/mediator/profile', labelKey: 'nav.profile', icon: 'UserCircle' },
  ],
  employee: [
    { key: 'dashboard', path: '/employee/dashboard', labelKey: 'nav.dashboard', icon: 'LayoutDashboard', permission: 'EMPLOYEE_DASHBOARD_VIEW' },
    { key: 'properties', path: '/employee/properties', labelKey: 'nav.properties', icon: 'Building2', permission: 'PROPERTY_MODERATION_VIEW' },
    { key: 'new-property', path: '/employee/properties/new', labelKey: 'nav.addProperty', icon: 'PlusSquare', permission: 'PROPERTY_MODERATION_VIEW' },
    { key: 'enquiries', path: '/employee/enquiries', labelKey: 'nav.enquiries', icon: 'Inbox', permission: 'ENQUIRY_VIEW' },
    { key: 'visits', path: '/employee/visits', labelKey: 'nav.visits', icon: 'CalendarCheck', permission: 'VISIT_VIEW' },
    { key: 'follow-ups', path: '/employee/follow-ups', labelKey: 'nav.followUps', icon: 'PhoneCall', permission: 'FOLLOWUP_VIEW' },
    { key: 'notifications', path: '/employee/notifications', labelKey: 'nav.notifications', icon: 'Bell', permission: 'NOTIFICATIONS_VIEW' },
    { key: 'reports', path: '/employee/reports', labelKey: 'nav.reports', icon: 'BarChart3', permission: 'REPORTS_VIEW' },
    { key: 'profile', path: '/employee/profile', labelKey: 'nav.profile', icon: 'UserCircle' },
  ],
  admin: [
    { key: 'dashboard', path: '/admin/dashboard', labelKey: 'nav.dashboard', icon: 'LayoutDashboard' },
    { key: 'registrations', path: '/admin/registrations', labelKey: 'nav.registrations', icon: 'UserPlus' },
    { key: 'users', path: '/admin/users', labelKey: 'nav.users', icon: 'Users' },
    { key: 'employees', path: '/admin/employees', labelKey: 'nav.employees', icon: 'IdCard' },
    { key: 'assignments', path: '/admin/assignments', labelKey: 'nav.assignments', icon: 'Briefcase' },
    { key: 'properties', path: '/admin/properties', labelKey: 'nav.properties', icon: 'Building2' },
    { key: 'new-property', path: '/admin/properties/new', labelKey: 'nav.addProperty', icon: 'PlusSquare' },
    { key: 'categories', path: '/admin/categories', labelKey: 'nav.categories', icon: 'Tags' },
    { key: 'media-rules', path: '/admin/media-rules', labelKey: 'nav.mediaRules', icon: 'ImagePlus' },
    { key: 'cms', path: '/admin/cms', labelKey: 'nav.cms', icon: 'FileText' },
    { key: 'enquiries', path: '/admin/enquiries', labelKey: 'nav.enquiries', icon: 'Inbox' },
    { key: 'visits', path: '/admin/visits', labelKey: 'nav.visits', icon: 'CalendarCheck' },
    { key: 'follow-ups', path: '/admin/follow-ups', labelKey: 'nav.followUps', icon: 'PhoneCall' },
    { key: 'reports', path: '/admin/reports', labelKey: 'nav.reports', icon: 'BarChart3' },
    { key: 'notifications', path: '/admin/notifications', labelKey: 'nav.notifications', icon: 'Bell' },
    { key: 'audit-logs', path: '/admin/audit-logs', labelKey: 'nav.auditLogs', icon: 'History' },
    { key: 'property-fields', path: '/admin/property-fields', labelKey: 'nav.propertyFields', icon: 'Sliders' },
    { key: 'registration-forms', path: '/admin/registration-forms', labelKey: 'nav.registrationForms', icon: 'ClipboardList' },
    { key: 'settings', path: '/admin/settings', labelKey: 'nav.settings', icon: 'Settings' },
  ],
};

export const ROLE_HOME = {
  buyer: '/buyer/dashboard',
  seller: '/seller/dashboard',
  mediator: '/mediator/dashboard',
  employee: '/employee/dashboard',
  admin: '/admin/dashboard',
};
