export const PROFILE_MENU = {
  buyer: [
    { key: 'myProfile', path: '/buyer/profile', labelKey: 'profileMenu.myProfile', icon: 'UserCircle' },
    { key: 'myProperties', path: '/buyer/my-properties', labelKey: 'profileMenu.myProperties', icon: 'Building2' },
    { key: 'addProperty', path: '/buyer/properties/new', labelKey: 'profileMenu.addProperty', icon: 'PlusSquare' },
    { key: 'wishlist', path: '/buyer/favourites', labelKey: 'profileMenu.wishlist', icon: 'Heart' },
    { key: 'interestedProperties', path: '/buyer/interests', labelKey: 'profileMenu.interestedProperties', icon: 'MessageSquareHeart' },
    { key: 'scheduleVisits', path: '/buyer/visits', labelKey: 'profileMenu.scheduleVisits', icon: 'CalendarCheck' },
    { key: 'notifications', path: '/buyer/notifications', labelKey: 'profileMenu.notifications', icon: 'Bell' },
    { key: 'settings', path: '/buyer/settings', labelKey: 'profileMenu.settings', icon: 'Settings' },
  ],
  seller: [
    { key: 'myProfile', path: '/seller/profile', labelKey: 'profileMenu.myProfile', icon: 'UserCircle' },
    { key: 'myProperties', path: '/seller/properties', labelKey: 'profileMenu.myProperties', icon: 'Building2' },
    { key: 'addProperty', path: '/seller/properties/new', labelKey: 'profileMenu.addProperty', icon: 'PlusSquare' },
    { key: 'propertyEnquiries', path: '/seller/enquiries', labelKey: 'profileMenu.propertyEnquiries', icon: 'Inbox' },
    { key: 'visits', path: '/seller/visits', labelKey: 'profileMenu.visits', icon: 'CalendarCheck' },
    { key: 'analytics', path: '/seller/analytics', labelKey: 'profileMenu.analytics', icon: 'BarChart3' },
    { key: 'notifications', path: '/seller/notifications', labelKey: 'profileMenu.notifications', icon: 'Bell' },
    { key: 'settings', path: '/seller/settings', labelKey: 'profileMenu.settings', icon: 'Settings' },
  ],
  mediator: [
    { key: 'myProfile', path: '/mediator/profile', labelKey: 'profileMenu.myProfile', icon: 'UserCircle' },
    { key: 'assignedProperties', path: '/mediator/properties', labelKey: 'profileMenu.assignedProperties', icon: 'Building2' },
    { key: 'addProperty', path: '/mediator/properties/new', labelKey: 'profileMenu.addProperty', icon: 'PlusSquare' },
    { key: 'clientLeads', path: '/mediator/leads', labelKey: 'profileMenu.clientLeads', icon: 'Users' },
    { key: 'visits', path: '/mediator/visits', labelKey: 'profileMenu.visits', icon: 'CalendarCheck' },
    { key: 'commissionHistory', path: '/mediator/commission', labelKey: 'profileMenu.commissionHistory', icon: 'HandCoins' },
    { key: 'notifications', path: '/mediator/notifications', labelKey: 'profileMenu.notifications', icon: 'Bell' },
    { key: 'settings', path: '/mediator/settings', labelKey: 'profileMenu.settings', icon: 'Settings' },
  ],
  admin: [
    { key: 'dashboard', path: '/admin/dashboard', labelKey: 'profileMenu.dashboard', icon: 'LayoutDashboard' },
    { key: 'users', path: '/admin/users', labelKey: 'profileMenu.users', icon: 'Users' },
    { key: 'properties', path: '/admin/properties', labelKey: 'profileMenu.properties', icon: 'Building2' },
    { key: 'employeeManagement', path: '/admin/employees', labelKey: 'profileMenu.employeeManagement', icon: 'IdCard' },
    { key: 'analytics', path: '/admin/reports', labelKey: 'profileMenu.analytics', icon: 'BarChart3' },
    { key: 'reports', path: '/admin/reports', labelKey: 'profileMenu.reports', icon: 'FileBarChart' },
    { key: 'cms', path: '/admin/cms', labelKey: 'profileMenu.cms', icon: 'FileText' },
    { key: 'settings', path: '/admin/settings', labelKey: 'profileMenu.settings', icon: 'Settings' },
  ],
  employee: [
    { key: 'dashboard', path: '/employee/dashboard', labelKey: 'profileMenu.dashboard', icon: 'LayoutDashboard' },
    { key: 'assignedVerifications', path: '/employee/verifications', labelKey: 'profileMenu.assignedVerifications', icon: 'BadgeCheck' },
    { key: 'propertyModeration', path: '/employee/properties', labelKey: 'profileMenu.propertyModeration', icon: 'Building2' },
    { key: 'assignedEnquiries', path: '/employee/enquiries', labelKey: 'profileMenu.assignedEnquiries', icon: 'Inbox' },
    { key: 'visits', path: '/employee/visits', labelKey: 'profileMenu.visits', icon: 'CalendarCheck' },
    { key: 'followUps', path: '/employee/follow-ups', labelKey: 'profileMenu.followUps', icon: 'PhoneCall' },
    { key: 'notifications', path: '/employee/notifications', labelKey: 'profileMenu.notifications', icon: 'Bell' },
    { key: 'profile', path: '/employee/profile', labelKey: 'profileMenu.myProfile', icon: 'UserCircle' },
  ],
};

export const PROFILE_ROUTE = {
  buyer: '/buyer/profile',
  seller: '/seller/profile',
  mediator: '/mediator/profile',
  admin: '/admin/settings',
  employee: '/employee/profile',
};
