export const TE_TRANSLATIONS = {
  'Residential Property Details': 'నివాస ఆస్తి వివరాలు',
  'Land Details': 'భూమి వివరాలు',
  'Please provide structure specifications, category-specific details, and document uploads.': 'దయచేసి నిర్మాణ లక్షణాలు, వర్గ-నిర్దిష్ట వివరాలు మరియు పత్రాలను అందించండి.',
  '1. Layout & Room Counters': '1. లేఅవుట్ & గదుల లెక్కింపు',
  '2. Category-Specific Details': '2. వర్గ-నిర్దిష్ట వివరాలు',
  '1. Property Details': '1. ఆస్తి వివరాలు',
  'Schedule / Boundaries': 'షెడ్యూల్ / సరిహద్దులు',
  'Land Length': 'భూమి పొడవు',
  'Land Width': 'భూమి వెడల్పు',
  'Schedule A': 'షెడ్యూల్ ఎ',
  'Schedule B': 'షెడ్యూల్ బి',
  'Schedule C': 'షెడ్యూల్ సి',
  'Yes': 'అవును',
  'No': 'కాదు',
  'Ground Sq Yards': 'గ్రౌండ్ స్క్వేర్ యార్డులు',
  'Sq Yards': 'చదరపు గజాలు',
  'Acre': 'ఎకరం',
  'Total Valuation': 'మొత్తం విలువ',
  '3. Dimensions & Borders (Optional)': '3. కొలతలు & సరిహద్దులు (ఐచ్ఛికం)',
  '2. Dimensions & Borders (Optional)': '2. కొలతలు & సరిహద్దులు (ఐచ్ఛికం)',
  'Additional Details': 'అదనపు వివరాలు',
  'Select...': 'ఎంచుకోండి...',
  'Other (type your own)': 'ఇతర (మీ స్వంతంగా టైప్ చేయండి)',
  'Enter': 'నమోదు చేయండి',
  'Type your own': 'మీ స్వంతంగా టైప్ చేయండి',
  'Feet': 'అడుగులు',
  'boundary details': 'సరిహద్దు వివరాలు',
  'No sub-parts configured.': 'ఉప-భాగాలు కాన్ఫిగర్ చేయబడలేదు.',
  'Shown for:': 'దీని కోసం చూపబడుతోంది:',
  'Amenities section is disabled.': 'సౌకర్యాల విభాగం డిసేబుల్ చేయబడింది.',
  'Total floors in building': 'భవనంలో మొత్తం అంతస్తులు',
  'Floor number of this property': 'ఈ ఆస్తి ఫ్లోర్ నంబర్',
  'e.g. Car / Bike parking availability': 'ఉదా. కార్ / బైక్ పార్కింగ్ లభ్యత',
  'e.g. New / 2 years old': 'ఉదా. కొత్త / 2 సంవత్సరాలు',
  'e.g. Fencing / Compound wall': 'ఉదా. ఫెన్సింగ్ / కాంపౌండ్ వాల్',
  'e.g. Block A, Tower 2': 'ఉదా. బ్లాక్ ఎ, టవర్ 2',
  'East boundary details': 'తూర్పు సరిహద్దు వివరాలు',
  'South boundary details': 'దక్షిణం సరిహద్దు వివరాలు',
  'West boundary details': 'పడమర సరిహద్దు వివరాలు',
  'North boundary details': 'ఉత్తరం సరిహద్దు వివరాలు',

  'Plot Area': 'ప్లాట్ విస్తీర్ణం',
  'Area Unit': 'విస్తీర్ణం యూనిట్',
  'Price per Sq.Yard': 'చదరపు గజం ధర',
  'Length': 'పొడవు',
  'Width': 'వెడల్పు',
  'Plot Number': 'ప్లాట్ నంబర్',
  'Facing': 'దిక్కు',
  'Road Width': 'రహదారి వెడల్పు',
  'Corner Plot': 'కార్నర్ ప్లాట్',
  'Boundary Wall': 'సరిహద్దు గోడ',
  'Approval Type': 'ఆమోద రకం',
  'Layout Name': 'లేఅవుట్ పేరు',
  'Survey Number': 'సర్వే నంబర్',
  'Ownership Type': 'యాజమాన్య రకం',
  'Registration Status': 'రిజిస్ట్రేషన్ స్థితి',
  'Loan Availability': 'రుణ లభ్యత',
  'Property Type': 'ఆస్తి రకం',
  'Built-up Area': 'నిర్మిత విస్తీర్ణం',
  'Carpet Area': 'కార్పెట్ విస్తీర్ణం',
  'Floor Number': 'ఫ్లోర్ నంబర్',
  'Total Floors': 'మొత్తం అంతస్తులు',
  'Frontage': 'ముందు భాగం',
  'Ceiling Height': 'పైకప్పు ఎత్తు',
  'Furnishing': 'ఫర్నిషింగ్',
  'Washrooms': 'వాష్‌రూమ్‌లు',
  'Parking': 'పార్కింగ్',
  'Property Age': 'ఆస్తి వయస్సు',
  'Maintenance Charges': 'మెయింటెనెన్స్ ఛార్జీలు',
  'Suitable Business Type': 'అనుకూల వ్యాపార రకం',
  'Super Built-up Area': 'సూపర్ బిల్ట్-అప్ విస్తీర్ణం',
  'Total Flats': 'మొత్తం ఫ్లాట్‌లు',
  'Tower / Block Name': 'టవర్ / బ్లాక్ పేరు',
  'Flat Number': 'ఫ్లాట్ నంబర్',
  'Flats per Floor': 'ఫ్లోర్‌కి ఫ్లాట్‌లు',
  'Construction Year': 'నిర్మాణ సంవత్సరం',
  'Possession Status': 'స్వాధీన స్థితి',
  'Possession Date': 'స్వాధీన తేదీ',
  'Property Status': 'ఆస్తి స్థితి',
  'Water Source': 'నీటి వనరు',
  'Parking Count': 'పార్కింగ్ సంఖ్య',
  'Approval Details': 'ఆమోద వివరాలు',
  'RERA Number': 'రీరా నంబర్',
  'Bedrooms': 'బెడ్‌రూమ్‌లు',
  'Bathrooms': 'బాత్‌రూమ్‌లు',
  'Balconies': 'బాల్కనీలు',
  'Number of Floors': 'అంతస్తుల సంఖ్య',
  'Corner Property': 'కార్నర్ ఆస్తి',
  'Electricity': 'విద్యుత్తు',
  'BHK': 'బిహెచ్‌కె',
  'Maintenance Charges (Monthly)': 'నెలసరి మెయింటెనెన్స్ ఛార్జీలు',
  'Project Name': 'ప్రాజెక్ట్ పేరు',
  'Venture Name': 'వెంచర్ పేరు',
  'Total Area': 'మొత్తం విస్తీర్ణం',
  'Available Plot Sizes': 'అందుబాటులో ఉన్న ప్లాట్ సైజులు',
  'Total Plots': 'మొత్తం ప్లాట్‌లు',
  'Available Plots': 'అందుబాటులో ఉన్న ప్లాట్‌లు',
  'Amenities': 'సౌకర్యాలు',
  'Land Area': 'భూమి విస్తీర్ణం',
  'Price Type': 'ధర రకం',
  'Nearby City': 'సమీప నగరం',
  'Land Type': 'భూమి రకం',
  'Soil Type': 'నేల రకం',
  'Road Facing': 'రహదారి వైపు',
  'Land Facing': 'భూమి దిక్కు',
  'Water Availability': 'నీటి లభ్యత',
  'Electricity Availability': 'విద్యుత్తు లభ్యత',
  'Borewell Count': 'బోరుబావి సంఖ్య',
  'Agricultural Electricity Connection': 'వ్యవసాయ విద్యుత్తు కనెక్షన్',
  'Boundary / Fencing': 'సరిహద్దు / ఫెన్సింగ్',
  'Land Shape': 'భూమి ఆకారం',
  'Approach Road Type': 'ప్రవేశ రహదారి రకం',
  'Tar Road': 'తారు రోడ్డు',
  'Govt Donka': 'ప్రభుత్వ డొంక',
  'Private Donka': 'ప్రైవేట్ డొంక',
  'No Roads': 'రోడ్లు లేవు',
  'Distance from Main Road': 'ప్రధాన రహదారి నుండి దూరం',
  'Farm Type': 'ఫారం రకం',
  'Borewell': 'బోరుబావి',
  'Road Access': 'రోడ్డు యాక్సెస్',
  'Fencing': 'ఫెన్సింగ్',
  'Farm House': 'ఫారం హౌస్',
  'Crops/Trees': 'పంటలు/చెట్లు',
  'Price per Acre / Sq.Yard': 'ఎకరా / చదరపు గజానికి ధర',
  'Industrial Approval': 'పారిశ్రామిక ఆమోదం',
  'Highway Distance': 'హైవే దూరం',
  'Electricity Capacity': 'విద్యుత్తు సామర్థ్యం',
  'Suitable Industry Type': 'అనుకూల పరిశ్రమ రకం',
  'Open Area': 'ఓపెన్ ప్రాంతం',
  'Entry Gate Width': 'ప్రవేశ గేట్ వెడల్పు',
  'Floor Load Capacity': 'ఫ్లోర్ లోడ్ సామర్థ్యం',
  'Parking Area': 'పార్కింగ్ ప్రాంతం',
  'Loading / Unloading Area': 'లోడింగ్ / అన్‌లోడింగ్ ప్రాంతం',
  'Power Availability': 'పవర్ లభ్యత',
  'Security Deposit': 'సెక్యూరిటీ డిపాజిట్',
  'Total Land Area': 'మొత్తం భూమి విస్తీర్ణం',

  'North': 'ఉత్తరం',
  'South': 'దక్షిణం',
  'East': 'తూర్పు',
  'West': 'పడమర',
  'North-East': 'ఈశాన్యం',
  'North-West': 'వాయువ్యం',
  'South-East': 'ఆగ్నేయం',
  'South-West': 'నైరుతి',
  'Unfurnished': 'అన్‌ఫర్నిష్డ్',
  'Semi-furnished': 'సెమీ-ఫర్నిష్డ్',
  'Semi-Furnished': 'సెమీ-ఫర్నిష్డ్',
  'Furnished': 'ఫర్నిష్డ్',
  'Fully-Furnished': 'ఫుల్లీ-ఫర్నిష్డ్',
  'Covered': 'కవర్డ్',
  'Open': 'ఓపెన్',
  'Both': 'రెండూ',
  'None': 'ఏదీ లేదు',
  'Car': 'కార్',
  'Bike': 'బైక్',
  'Basement': 'బేస్‌మెంట్',
  'Stilt': 'స్టిల్ట్',
  'Multi-level': 'బహుళ స్థాయి',
  'Sq. Ft': 'చ.అ.',
  'Sq. Yd': 'చ.గజం',
  'Acres': 'ఎకరాలు',
  'Cents': 'సెంట్లు',
  'Gunta': 'గుంట',
  'Guntasha': 'గుంటశ',
  'Sq. M': 'చ.మీ',
  'Guntas': 'గుంటలు',
  'Sq. Yards': 'చదరపు గజాలు',
  'Hectares': 'హెక్టార్లు',
  'Red Soil': 'ఎర్ర నేల',
  'Black Soil': 'నల్ల నేల',
  'Sandy': 'ఇసుక నేల',
  'Loamy': 'లోమీ నేల',
  'Clay': 'బంకమట్టి',
  'Other': 'ఇతర',
  'Freehold': 'ఫ్రీహోల్డ్',
  'Leasehold': 'లీజ్‌హోల్డ్',
  'Co-operative': 'సహకార',
  'Others': 'ఇతరాలు',
  'Registered': 'రిజిస్టర్డ్',
  'Unregistered': 'రిజిస్టర్ కానిది',
  'Registration Pending': 'రిజిస్ట్రేషన్ పెండింగ్',
  'DTCP': 'డిటిసిపి',
  'CRDA': 'సిఆర్‌డిఎ',
  'RERA': 'రీరా',
  'Panchayat': 'పంచాయతీ',
  'Municipality': 'మునిసిపాలిటీ',
  'Ready to Move': 'రెడీ టు మూవ్',
  'Under Construction': 'నిర్మాణంలో ఉంది',
  'Completed (Occupation Fit)': 'పూర్తయింది',
  'Shop': 'షాప్',
  'Office': 'ఆఫీస్',
  'Showroom': 'షోరూమ్',
  'Complex': 'కాంప్లెక్స్',
  'Retail': 'రిటైల్',
  'Food': 'ఫుడ్',
  'Healthcare': 'హెల్త్‌కేర్',
  'Education': 'విద్య',
  'Bank': 'బ్యాంక్',
  'Warehouse': 'వేర్‌హౌస్',
  'New Property': 'కొత్త ఆస్తి',
  'Resale': 'రీసేల్',
  'Municipal': 'మునిసిపల్',
  'Well': 'బావి',
  'Tanker': 'ట్యాంకర్',
  'Multiple': 'బహుళ',
  'Canal': 'కాలువ',
  'River': 'నది',
  'Pond': 'చెరువు',
  'Industrial Water': 'పారిశ్రామిక నీరు',
  'Wet Land': 'తడి భూమి',
  'Dry Land': 'మెట్ట భూమి',
  'Farm Land': 'వ్యవసాయ భూమి',
  'Garden': 'తోట',
  'Plantation': 'ప్లాంటేషన్',
  'Good': 'మంచిది',
  'Moderate': 'మధ్యస్థం',
  'Scarce': 'తక్కువ',
  'Square': 'చతురస్రం',
  'Rectangular': 'దీర్ఘచతురస్రం',
  'Regular': 'సాధారణ',
  'Irregular': 'క్రమరహితం',
  'BT Road': 'బీటీ రోడ్డు',
  'CC Road': 'సీసీ రోడ్డు',
  'Mud Road': 'మట్టి రోడ్డు',
  'Organic': 'ఆర్గానిక్',
  'Traditional': 'సాంప్రదాయ',
  'Horticulture': 'ఉద్యానవనం',
  'Mixed': 'మిశ్రమం',
  'Total Price': 'మొత్తం ధర',
  'Per Acre': 'ఎకరానికి',
  'Per Cent': 'సెంటుకి',
  'APIIC': 'ఎపిఐఐసి',
  'HMDA': 'హెచ్‌ఎమ్‌డిఎ',
  'Villa': 'విల్లా',
  'Duplex': 'డూప్లెక్స్',
  'Triplex': 'ట్రిప్లెక్స్',
  'Row House': 'రో హౌస్',

  'Lift': 'లిఫ్ట్',
  'Power Backup': 'పవర్ బ్యాకప్',
  'Generator': 'జనరేటర్',
  'Car Parking': 'కార్ పార్కింగ్',
  'Visitor Parking': 'సందర్శకుల పార్కింగ్',
  'Security': 'సెక్యూరిటీ',
  'CCTV': 'సీసీటీవీ',
  'Swimming Pool': 'స్విమ్మింగ్ పూల్',
  'Gym': 'జిమ్',
  'Club House': 'క్లబ్ హౌస్',
  'Children Play Area': 'పిల్లల ఆట స్థలం',
  'Community Hall': 'కమ్యూనిటీ హాల్',
  'Indoor Games': 'ఇండోర్ గేమ్స్',
  'Outdoor Games': 'అవుట్‌డోర్ గేమ్స్',
  'Walking Track': 'వాకింగ్ ట్రాక్',
  'Intercom': 'ఇంటర్‌కామ్',
  'Fire Safety': 'ఫైర్ సేఫ్టీ',
  'Rainwater Harvesting': 'వర్షపు నీటి సేకరణ',
  'Water Supply': 'నీటి సరఫరా',
  'Sewage Treatment Plant': 'మురుగునీటి శుద్ధి కేంద్రం',
  'Solar Power': 'సోలార్ పవర్',
  'Municipal Water': 'మునిసిపల్ నీరు',
  'Terrace': 'టెర్రస్',
  'Balcony': 'బాల్కనీ',
  'Modular Kitchen': 'మాడ్యులర్ కిచెన్',
  'Pooja Room': 'పూజా గది',
  'Store Room': 'స్టోర్ రూమ్',
  'Servant Room': 'సర్వెంట్ రూమ్',
  'Solar Water Heater': 'సోలార్ వాటర్ హీటర్',
  'Compound Wall': 'కాంపౌండ్ వాల్',
  'Gated Security': 'గేటెడ్ సెక్యూరిటీ',
  'Landscaped Garden': 'ల్యాండ్‌స్కేప్ గార్డెన్',
  'Street Lights': 'వీధి దీపాలు',
  'Supermarket': 'సూపర్‌మార్కెట్',
  'Temple': 'దేవాలయం',
  'Sports Area': 'క్రీడా ప్రాంతం',
  'Central AC': 'సెంట్రల్ ఎసీ',
  'Reception': 'రిసెప్షన్',
  'Conference Room': 'కాన్ఫరెన్స్ రూమ్',
  'Pantry': 'ప్యాంట్రీ',
  'Internet Connectivity': 'ఇంటర్నెట్ కనెక్టివిటీ',
  'Gated Entrance': 'గేటెడ్ ప్రవేశం',
  'CC Roads': 'సీసీ రోడ్లు',
  'BT Roads': 'బీటీ రోడ్లు',
  'Underground Drainage': 'భూగర్భ డ్రైనేజీ',
  'Water Connection': 'నీటి కనెక్షన్',
  'Avenue Plantation': 'ఎవెన్యూ ప్లాంటేషన్',
  'Children Park': 'పిల్లల పార్క్',
  'Main Road Facing': 'ప్రధాన రహదారి వైపు',
  'Highway Access': 'హైవే యాక్సెస్',
  'Drainage': 'డ్రైనేజీ',
  'Parking Space': 'పార్కింగ్ స్థలం',
  'High Footfall Area': 'ఎక్కువ రద్దీ ప్రాంతం',
  'Public Transport Nearby': 'సమీపంలో పబ్లిక్ ట్రాన్స్‌పోర్ట్',
  'Loading / Unloading Access': 'లోడింగ్ / అన్‌లోడింగ్ యాక్సెస్',
  'Street Lighting': 'వీధి లైటింగ్',
  'Canal Water': 'కాలువ నీరు',
  'River Nearby': 'సమీపంలో నది',
  'Drip Irrigation': 'బిందు సేద్యం',
  'Transformer Nearby': 'సమీపంలో ట్రాన్స్‌ఫార్మర్',
  'Storage Shed': 'స్టోరేజ్ షెడ్',
  'Motor/Pump': 'మోటార్/పంపు',
  'Trees / Plantation': 'చెట్లు / తోట',
  'Main Road Access': 'ప్రధాన రహదారి యాక్సెస్',
  'Highway Nearby': 'సమీపంలో హైవే',
  '3-Phase Electricity': '3-ఫేజ్ విద్యుత్తు',
  'Transformer': 'ట్రాన్స్‌ఫార్మర్',
  'Heavy Vehicle Access': 'భారీ వాహన యాక్సెస్',
  'Loading Area': 'లోడింగ్ ప్రాంతం',
  'Truck Parking': 'ట్రక్ పార్కింగ్',
  'Loading Dock': 'లోడింగ్ డాక్',
  '3-Phase Power': '3-ఫేజ్ పవర్',
  'Office Room': 'ఆఫీస్ రూమ్',
  'Washroom': 'వాష్‌రూమ్',
  'Water': 'నీరు',
  'Farm Shed': 'ఫారం షెడ్',
  'Outdoor Seating': 'అవుట్‌డోర్ సీటింగ్',
};

export function getTe(text, language) {
  if (!text) return '';
  if (language !== 'te') return text;
  return TE_TRANSLATIONS[text] || text;
}